mpi_head:
    build: .
    #image: openmpi
    ports:
      - "22"
    links:
      - mpi_node
    volumes:
      - '.:/home/mpirun/mpi4py_benchmarks'

mpi_node:
    build: .
    volumes:
      - '.:/home/mpirun/mpi4py_benchmarks'
    #image: openmpi


# version: "2"

# services:
#   mpi_head:
#     build: .
#     # image: openmpi
#     ports:
#       - "22"
#     links:
#       - mpi_node
#     networks:
#       - net

#   mpi_node:
#     build: .
#     # image: openmpi
#     networks:
#       - net

# networks:
#   net:
#     driver: bridge
